name: NSE Automation Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '30 14 * * 1-5' # सोमवार से शुक्रवार हर शाम 8:00 PM IST (14:30 UTC) पर खुद चलेगा

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Repository Code
        uses: actions/checkout@v4

      - name: Load Python 3.11 Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Trading Libraries
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests urllib3 gspread oauth2client

      - name: Execute Live Tracker
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
        run: |
          echo "$MY_SECRET_KEY" > google_creds.json
          python final_script.py
