name: NSE Auto Refresh Daily

on:
  schedule:
    # 17:00 UTC = रात 10:30 बजे भारतीय समयानुसार (IST)
    - cron: '0 17 * * *'
  workflow_dispatch: # इससे आप जब चाहें खुद भी बटन दबाकर रन कर सकते हैं

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Code
      uses: actions/checkout@v4 # v3 से v4 पर अपग्रेड कर दिया

    - name: Load Python 3.11 Environment
      uses: actions/setup-python@v5 # v4 से v5 पर अपग्रेड कर दिया
      with:
        python-version: '3.11'
        
    - name: Install Trading Libraries
      run: |
        pip install pandas requests urllib3 gspread oauth2client openpyxl
        
    - name: Execute Live Tracker
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: python final_script.py
